- name: kubernetes-apps
  rules:
  - alert: KubePodCrashLooping
    annotations:
      summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
    expr: sum(rate(kube_pod_container_status_restarts_total{container!="metricbeat",container!="datadog",container!="hercules",job="kube-state-metrics",namespace=~".*"}[15m])) by (namespace) * 60 * 5 > 1
    for: 5m
    labels:
      severity: critical
      group: devops
  - alert: KubePodNotReady
    annotations:
      summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready
        state for longer than 15 minutes.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
    expr: sum by (namespace, pod) (max by(namespace, pod) (kube_pod_status_phase{job="kube-state-metrics",namespace=~".*", phase=~"Pending|Unknown"}) * on(namespace, pod) group_left(owner_kind) max by(namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"})) > 0
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: KubeDeploymentGenerationMismatch
    annotations:
      summary: Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment
        }} does not match, this indicates that the Deployment has failed but has
        not been rolled back.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
    expr: kube_deployment_status_observed_generation{job="kube-state-metrics", namespace=~".*"} != kube_deployment_metadata_generation{job="kube-state-metrics", namespace=~".*"}
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: KubeDeploymentReplicasMismatch
    annotations:
      summary: Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has not matched the expected number of replicas for longer than 15 minutes.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
    expr: kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~".*"} != kube_deployment_status_replicas_available{job="kube-state-metrics", namespace=~".*"}
    for: 20m
    labels:
      severity: critical
      group: devops
  - alert: KubeStatefulSetReplicasMismatch
    annotations:
      summary: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} has
        not matched the expected number of replicas for longer than 15 minutes.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch
    expr: kube_statefulset_status_replicas_ready{job="kube-state-metrics", namespace=~".*"} != kube_statefulset_status_replicas{job="kube-state-metrics", namespace=~".*"}
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: KubeStatefulSetGenerationMismatch
    annotations:
      summary: StatefulSet generation for {{ $labels.namespace }}/{{ $labels.statefulset }} does not match, this indicates that the StatefulSet has failed but has not been rolled back.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch
    expr: kube_statefulset_status_observed_generation{job="kube-state-metrics", namespace=~".*"} != kube_statefulset_metadata_generation{job="kube-state-metrics", namespace=~".*"}
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: KubeStatefulSetUpdateNotRolledOut
    annotations:
      summary: StatefulSet {{ $labels.namespace }}/{{ $labels.statefulset }} update has not been rolled out.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout
    expr: max without (revision) (kube_statefulset_status_current_revision{job="kube-state-metrics", namespace=~".*",namespace!~"observability"} unless kube_statefulset_status_update_revision{job="kube-state-metrics", namespace=~".*"})*(kube_statefulset_replicas{job="kube-state-metrics", namespace=~".*"} != kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"})
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: KubeDaemonSetRolloutStuck
    annotations:
      summary: Only {{ $value | humanizePercentage }} of the desired Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are scheduled and ready.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
    expr: kube_daemonset_status_number_ready{job="kube-state-metrics", namespace=~".*",daemonset!="metricbeat"} / kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*",daemonset!="metricbeat"} < 1.00
    for: 30m
    labels:
      severity: critical
      group: devops
  - alert: KubeContainerWaiting
    annotations:
      summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container}} has been in waiting state for longer than 1 hour.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting
    expr: sum by (namespace, pod, container) (kube_pod_container_status_waiting_reason{job="kube-state-metrics",namespace=~".*"}) > 0
    for: 1h
    labels:
      severity: warning
      group: devops
  - alert: KubeDaemonSetNotScheduled
    annotations:
      summary: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are not scheduled.'
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled
    expr: kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} - kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"} > 0
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: KubeDaemonSetMisScheduled
    annotations:
      summary: '{{ $value }} Pods of DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} are running where they are not supposed to run.'
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled
    expr: kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"} > 0
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: KubeCronJobRunning
    annotations:
      summary: CronJob {{ $labels.namespace }}/{{ $labels.cronjob }} is taking more than 1h to complete.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecronjobrunning
    expr: time() - kube_cronjob_next_schedule_time{job="kube-state-metrics", namespace=~".*"} > 3600
    for: 1h
    labels:
      severity: warning
      group: devops
  - alert: KubeJobCompletion
    annotations:
      summary: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than one hour to complete.
      titleLink: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobcompletion
    expr: kube_job_spec_completions{job="kube-state-metrics", namespace=~".*",namespace!~"observability",namespace!~"user-insights"} - kube_job_status_succeeded{job="kube-state-metrics", namespace=~".*",namespace!~"observability",namespace!~"user-insights"} > 0
    for: 1h
    labels:
      severity: warning
      group: devops
  - alert: KubeJobFailed
    annotations:
      summary: Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.
    expr: kube_job_failed{job="kube-state-metrics", namespace=~".*",namespace!~".*observability",namespace!="user-insights"}  > 0
    for: 15m
    labels:
      severity: warning
      group: devops
  - alert: KubeHpaReplicasMismatch
    annotations:
      summary: HPA {{ $labels.namespace }}/{{ $labels.hpa }} has not matched the desired number of replicas for longer than 15 minutes.
    expr: (kube_hpa_status_desired_replicas{job="kube-state-metrics", namespace=~".*"} != kube_hpa_status_current_replicas{job="kube-state-metrics", namespace=~".*"}) and changes(kube_hpa_status_current_replicas[15m]) == 0
    for: 15m
    labels:
      severity: warning
      group: devops
  - alert: KubeHpaMaxedOut
    annotations:
      summary: HPA {{ $labels.namespace }}/{{ $labels.hpa }} has been running at max replicas for longer than 15 minutes.
    expr: kube_hpa_status_current_replicas{job="kube-state-metrics", namespace=~".*",namespace!~"segmentation-service",namespace!~"observability",namespace!~"rashi",namespace!~"care-recommendation-service",namespace!~"cache-service",namespace!~"async-task-service.*",namespace!~"iris.*",namespace!="catalog-service"} == kube_hpa_spec_max_replicas{job="kube-state-metrics", namespace=~".*",namespace!~"observability",namespace!~"async-task-service.*",namespace!~"iris.*",namespace!="catalog-service",namespace!~"cache-service",namespace!~"care-recommendation-service",namespace!~"segmentation-service",namespace!~"rashi"}
    for: 15m
    labels:
      severity: warning
      group: devops
