- name: prometheus
  rules:
  - alert: PrometheusBadConfig
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to reload its configuration.
      summary: Failed Prometheus configuration reload.
    expr: max_over_time(prometheus_config_last_reload_successful{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) == 0
    for: 2m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusNotificationQueueRunningFull
    annotations:
      description: Alert notification queue of Prometheus {{$labels.namespace}}/{{$labels.pod}} is running full.
      summary: Prometheus alert notification queue predicted to run full in less than 30m.
    expr: (predict_linear(prometheus_notifications_queue_length{job=~"prometheus-operator.*",namespace="monitoring"}[5m], 60 * 30) > min_over_time(prometheus_notifications_queue_capacity{job=~"prometheus-operator.*",namespace="monitoring"}[5m]))
    for: 15m
    labels:
      severity: warning
      group: devops
  - alert: ErrorSendingAlertsToAlertmanager
    annotations:
      description: '{{ printf "%.1f" $value }}% errors while sending alerts from Prometheus {{$labels.namespace}}/{{$labels.pod}} to Alertmanager {{$labels.alertmanager}}.'
      summary: Prometheus has encountered more than 1% errors sending alerts to a specific Alertmanager.
    expr: (rate(prometheus_notifications_errors_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) / rate(prometheus_notifications_sent_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m])) * 100 > 1
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusErrorSendingAlertsToAnyAlertmanager
    annotations:
      description: '{{ printf "%.1f" $value }}% minimum errors while sending alerts from Prometheus {{$labels.namespace}}/{{$labels.pod}} to any Alertmanager.'
      summary: Prometheus encounters more than 3% errors sending alerts to any Alertmanager.
    expr: min without(alertmanager) (rate(prometheus_notifications_errors_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) / rate(prometheus_notifications_sent_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m])) * 100 > 3
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusNotConnectedToAlertmanagers
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is not connected to any Alertmanagers.
      summary: Prometheus is not connected to any Alertmanagers.
    expr: max_over_time(prometheus_notifications_alertmanagers_discovered{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) < 1
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusTSDBReloadsFailing
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has detected {{$value | humanize}} reload failures over the last 3h.
      summary: Prometheus has issues reloading blocks from disk.
    expr: increase(prometheus_tsdb_reloads_failures_total{job=~"prometheus-operator.*",namespace="monitoring"}[3h]) > 0
    for: 4h
    labels:
      severity: warning
      group: devops
  - alert: PrometheusTSDBCompactionsFailing
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has detected {{$value | humanize}} compaction failures over the last 3h.
      summary: Prometheus has issues compacting blocks.
    expr: increase(prometheus_tsdb_compactions_failed_total{job=~"prometheus-operator.*",namespace="monitoring"}[3h]) > 0
    for: 4h
    labels:
      severity: warning
      group: devops
  - alert: PrometheusNotIngestingSamples
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting samples.
      summary: Prometheus is not ingesting samples.
    expr: rate(prometheus_tsdb_head_samples_appended_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) <= 0
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusDuplicateTimestamps
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }} samples/s with different values but duplicated timestamp.
      summary: Prometheus is dropping samples with duplicate timestamps.
    expr: rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) > 0
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusOutOfOrderTimestamps
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is dropping {{ printf "%.4g" $value  }} samples/s with timestamps arriving out of order.
      summary: Prometheus drops samples with out-of-order timestamps.
    expr: rate(prometheus_target_scrapes_sample_out_of_order_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) > 0
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusRemoteStorageFailures
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} failed to send {{ printf "%.1f" $value }}% of the samples to queue {{$labels.queue}}.
      summary: Prometheus fails to send samples to remote storage.
    expr: (rate(prometheus_remote_storage_failed_samples_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) / (rate(prometheus_remote_storage_failed_samples_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) + rate(prometheus_remote_storage_succeeded_samples_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]))) * 100 > 1
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusRemoteWriteBehind
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} remote write is {{ printf "%.1f" $value }}s behind for queue {{$labels.queue}}.
      summary: Prometheus remote write is behind.
    expr: (max_over_time(prometheus_remote_storage_highest_timestamp_in_seconds{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) - on(job, instance) group_right max_over_time(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{job=~"prometheus-operator.*",namespace="monitoring"}[5m])) > 120
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusRuleFailures
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to  evaluate {{ printf "%.0f" $value }} rules in the last 5m.
      summary: Prometheus is failing rule evaluations.
    expr: increase(prometheus_rule_evaluation_failures_total{namespace="monitoring"}[5m]) > 0
    for: 15m
    labels:
      severity: critical
      group: devops
  - alert: PrometheusMissingRuleEvaluations
    annotations:
      description: Prometheus {{$labels.namespace}}/{{$labels.pod}} has missed {{ printf "%.0f" $value }} rule group evaluations in the last 5m.
      summary: Prometheus is missing rule evaluations due to slow rule group evaluation.
    expr: increase(prometheus_rule_group_iterations_missed_total{job=~"prometheus-operator.*",namespace="monitoring"}[5m]) > 0
    for: 15m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusOperatorReconcileErrors
    annotations:
      summary: Errors while reconciling {{ $labels.controller }} in {{ $labels.namespace }} Namespace.
    expr: rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator-operator",namespace="monitoring"}[5m]) > 0.1
    for: 10m
    labels:
      severity: warning
      group: devops
  - alert: PrometheusOperatorNodeLookupErrors
    annotations:
      summary: Errors while reconciling Prometheus in {{ $labels.namespace }} Namespace.
    expr: rate(prometheus_operator_node_address_lookup_errors_total{job="prometheus-operator-operator",namespace="monitoring"}[5m]) > 0.1
    for: 10m
    labels:
      severity: warning
      group: devops
