- name: velero-failures
  rules:
  - alert: VeleroBackupPartialFailures
    annotations:
      summary: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
    expr: |-
      velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
    for: 15m
    labels:
      severity: warning
      group: devops      
  - alert: VeleroBackupFailures
    annotations:
      summary: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
    expr: |-
      velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
    for: 15m
    labels:
      severity: critical
      group: devops    